# Generated by Django 4.2.4 on 2024-03-30 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('skills', models.TextField()),
                ('experience', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=200)),
                ('specialized_in', models.CharField(choices=[('front_end', 'Front End'), ('back_end', 'Back End'), ('full_stack', 'Full Stack')], max_length=200)),
                ('bio', models.TextField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
