# Generated by Django 4.2.5 on 2024-03-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('aadharimg', models.ImageField(null=True, upload_to='images')),
                ('aadharno', models.PositiveIntegerField()),
                ('usertype', models.CharField(default='coder', max_length=100)),
            ],
        ),
    ]
