# Generated by Django 4.2.5 on 2024-03-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='usertype',
            field=models.CharField(max_length=100),
        ),
    ]
