# Generated by Django 4.2.5 on 2024-04-03 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
