# Generated by Django 4.2.5 on 2024-03-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_coder_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='usertype',
            field=models.CharField(default='coder', max_length=100),
        ),
    ]
