# Generated by Django 4.2.5 on 2024-04-03 05:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_delete_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('adminapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('proof', models.FileField(null=True, upload_to='images')),
                ('profile', models.ImageField(null=True, upload_to='images')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('adminapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('skills_required', models.CharField(max_length=100)),
                ('budget', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.buyer')),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.coder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.PositiveIntegerField()),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.coder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.project')),
            ],
        ),
    ]
