# Generated by Django 4.2.5 on 2024-04-05 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='')),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.coder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.project')),
            ],
        ),
    ]
