# Generated by Django 4.2.5 on 2024-04-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_projectdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdoc',
            name='doc',
            field=models.FileField(upload_to='files'),
        ),
    ]
