# Generated by Django 4.2.5 on 2024-04-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_projectdoc_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.CreateModel(
            name='Collaborate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='files')),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.coder')),
            ],
        ),
    ]
