# Generated by Django 4.2.5 on 2024-04-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_bid_status_collaborate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='progress',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On progress', 'On progress'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
