# Generated by Django 4.2.5 on 2024-04-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_bid_progress_alter_bid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='files')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.bid')),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.coder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.project')),
            ],
        ),
    ]
