# Generated by Django 4.2.5 on 2024-04-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_biddetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDoc',
        ),
    ]
