# Generated by Django 4.2.5 on 2024-04-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_delete_projectdoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddetails',
            name='project',
        ),
    ]
