# Generated by Django 4.2.5 on 2024-04-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_remove_biddetails_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
