# Generated by Django 4.2.5 on 2024-04-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_bid_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
