# Generated by Django 4.2.5 on 2024-04-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_remove_payment_project_payment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminapp.bid'),
        ),
    ]
