# Generated by Django 4.2.5 on 2024-04-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_alter_payment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='rating',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
