# Generated by Django 4.2.5 on 2024-04-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_coder_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
