# Generated by Django 4.2.5 on 2024-04-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_payment_is_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund',
            field=models.BooleanField(default=False),
        ),
    ]
