# Generated by Django 4.2.5 on 2024-04-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_payment_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_released',
            field=models.BooleanField(default=False),
        ),
    ]
