# Generated by Django 4.2.5 on 2024-04-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_payment_refund_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='aadhar_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='aadhar_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='pan_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='pan_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coder',
            name='aadhar_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='coder',
            name='aadhar_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coder',
            name='pan_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='coder',
            name='pan_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
