# Generated by Django 4.2.5 on 2024-04-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_buyer_aadhar_image_buyer_aadhar_no_buyer_pan_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coder',
            name='proof',
        ),
    ]
