# Generated by Django 4.2.5 on 2024-04-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_remove_coder_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.buyer')),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.coder')),
            ],
        ),
    ]
