# Generated by Django 4.2.5 on 2024-04-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='coder',
        ),
    ]
