# Generated by Django 4.2.5 on 2024-04-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_remove_feedback_coder'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
