# Generated by Django 4.2.5 on 2024-04-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyerapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyerProfile',
        ),
    ]
